name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (advanced features for building multi-platform Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to GitHub Container Registry (GHCR) using a GitHub token
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }} # This automatically gets the GitHub username
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}} # GH_TOKEN should be a repository secret

      # Build and push the Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/product-sentiment-analysis:v1 .
          docker push ghcr.io/${{ github.repository }}/product-sentiment-analysis:v1

