name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for building multi-platform Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }} # Use the GitHub username
          password: ${{ secrets.GH_TOKEN }} # Ensure GH_TOKEN is set in the repository secrets

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/product-sentiment-analysis:v1 .
          docker push ghcr.io/${{ github.repository }}/product-sentiment-analysis:v1
