name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: cayanide
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/cayanide/product-sentiment-analysis:v1 .
          docker push ghcr.io/cayanide/product-sentiment-analysis:v1
